# Generated by Django 4.2.13 on 2024-05-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_person_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='answers',
            new_name='score',
        ),
    ]
