# Generated by Django 4.2.13 on 2024-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_answers_person_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
